### PR TITLE
Testing Issue 43

### LINKED ISSUE #43: [BUG] Version 2.1.3 causes PHP Fatal Error
**Describe the bug**

Bump from version 2.1.2 -> 2.1.3 causes PHP Fatal Error. Same behaviour on three different sites.

**The Context**

PHP Fatal error:  Uncaught Error: Class 'lewiscowles\Plugins\EnableSVG\lewiscowles\WordPress\Compat\FileTypes\SVGSupport' not found in /var/www/html/wp-content/plugins/enable-svg-uploads/index.php:42

Stack trace:
#0 /var/www/html/wp-settings.php(391): include_once()
#1 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1237): require('/var/www/html/w...')
#2 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1158): WP_CLI\Runner->load_wordpress()
#3 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Bootstrap/LaunchRunner.php(23): WP_CLI\Runner->start()
#4 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/bootstrap.php(74): WP_CLI\Bootstrap\LaunchRunner->process(Object(WP_CLI\Bootstrap\BootstrapState))
#5 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/wp-cli.php(27): WP_CLI\bootstrap()
#6 phar:///usr/local/bin/wp/php/boot-phar.php(11): include('phar:///usr/loc...')
#7 /usr/local/bin/wp(4): include('phar:///usr/loc...')
#8 {main}
  thrown in /var/www/html/wp-content/plugins/enable-svg-uploads/index.php on line 42
  
**To Reproduce**

Steps to reproduce the behaviour:
Install latest version of plugin

**Expected behaviour**

Expectation is that plugin would work. Rolling back to version 2.1.2. eliminates problem.

### PR DESCRIPTION
**Pull request by Lewiscowles1986**
Require autoloader before requiring plugin php

Should fix #43 (can't reproduce. Perhaps is something to do with wp-cli)

### CODE REVIEW

File: src/index.php [hunk 1]
```diff
@@ -35,10 +35,10 @@
 	die();
 }
 
+require_once __DIR__ . '/vendor/autoload.php';
 require_once __DIR__ . '/lib/svgsupport.php';
 
 if ( defined( 'ABSPATH' ) ) {
-	include_once __DIR__ . '/vendor/autoload.php';
```
Comment (Lewiscowles1986) [inline src/index.php:41]: I think this was obscuring the root cause. we were only autoloading if `ABSPATH` was defined, which seems silly.

This was to work around test-suite not snapshot-ing the vendor-ing. I'll just be more straightforward.

Update: This was not the root cause. The root cause was complex and simple...

* Missing a leading slash before a class-name.
* Weird branching include / require logic.
* Test / CI being different to production
* Caching on manual test site

**Comment by Lewiscowles1986** [comment]
test pr comment

**Comment by Lewiscowles1986** [comment]
Look ma, I'm a comment

**Comment by Lewiscowles1986** [comment]
Dennis! Dennis... Dennis... Dennnis, Dennis, Dennis, Dennis!
